#:schema https://developers.openai.com/codex/config-schema.json
model_reasoning_effort = "low"
personality = "pragmatic"
forced_login_method = "chatgpt"
model = "gpt-5.5"
web_search = "live"
notify = ["$HOME/.codex/hooks/notify-terminal-notifier.sh"]
suppress_unstable_features_warning = true
plan_mode_reasoning_effort = "high"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[features]
shell_snapshot = true
multi_agent_v2 = true
prevent_idle_sleep = true
js_repl = true
hooks = true
undo = true
tool_search = true
remote_control = true
memories = false
chronicle = false

[feedback]
enabled = false

[sandbox_workspace_write]
network_access = true

[tui]
status_line = [
  "model-with-reasoning",
  "project-root",
  "git-branch",
  "context-used",
  "five-hour-limit",
  "weekly-limit",
  "codex-version",
]
theme = "catppuccin-latte"

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."google-calendar@openai-curated"]
enabled = false

[plugins."gmail@openai-curated"]
enabled = false

[plugins."github@openai-curated"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."claude-md-management@claude-plugins-official"]
enabled = false

[plugins."code-review@claude-plugins-official"]
enabled = false

[plugins."code-simplifier@claude-plugins-official"]
enabled = true

[plugins."context7@claude-plugins-official"]
enabled = false

[plugins."feature-dev@claude-plugins-official"]
enabled = true

[plugins."figma@claude-plugins-official"]
enabled = false

[plugins."frontend-design@claude-plugins-official"]
enabled = true

[plugins."plugin-dev@claude-plugins-official"]
enabled = false

[plugins."pr-review-toolkit@claude-plugins-official"]
enabled = false

[plugins."slack@claude-plugins-official"]
enabled = false

[plugins."terraform@claude-plugins-official"]
enabled = false

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."github@claude-plugins-official"]
enabled = false

[plugins."superpowers@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[marketplaces.claude-plugins-official]
last_updated = "2026-05-11T01:39:50Z"
last_revision = "00679aef889efe36bb0389f81d70b6229a2013ee"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[mcp_servers.xcode]
args = ["mcpbridge"]
command = "xcrun"
enabled = true

[hooks.state]

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:fbce185f06778f6935e18e60df59bbaeb3ba05d558ba9dfbe64b8133f5ce68fb"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:pre_tool_use:0:1"]
trusted_hash = "sha256:834b651aa08dfd2df53a7236deeea5833d288e73624e6265cff78ea1dd38d3fd"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:5d1ae6f116fa0b65e1e69653956185b504f1a0fc00b7d6c3f26bce68f17eff2f"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:3988b809d1a46c97a9c5405712be87db63906a51f9467c7ca88ce36b60b649a5"

[hooks.state."/Users/nasuno.ayumu/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:f80728ad206e6647577d90719509022f480a805fe1872bc844eefe51fa36fe13"

[memories]
generate_memories = false
use_memories = false

[projects."/Users/nasuno.ayumu/dev/github.com/luvpame/dotfiles"]
trust_level = "trusted"
